services:
  server:
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://harshwwe555:NNJVL9HZuIn21s9C@cluster0.nqx939g.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    restart: unless-stopped
    volumes:
      -  /home/ec2-user/Bookstore/uploads:/app/uploads

volumes:
  mongodb_data:
