services:
  server:
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://harshwwe555:r5J8XlSsJh1i6bYh@book.zsxhcka.mongodb.net/?retryWrites=true&w=majority&appName=book
    restart: unless-stopped
    volumes:
      -  /home/ec2-user/Bookstore/uploads:/app/uploads

volumes:
  mongodb_data:
